import { promises as fs } from 'fs'
import * as path from 'path'
import { safeResolveInVault, toRelative } from '../paths'
import { store } from '../../store'

const CLAUDE_MD = `# Project

> Auto-generated by Marrow. Edit this file to describe the project for Claude Code.

## Context

- **Purpose**:
- **Stack**:

## Guidelines

-
`

const README_MD = `# Project

_Add a project description here._
`

export async function toolCreateFolder(args: {
  path: string
  initialize_project?: boolean
}) {
  const vaultPath = store.get('vaultPath') as string | undefined
  if (!vaultPath) throw new Error('No vault configured')

  const absPath = await safeResolveInVault(vaultPath, args.path)

  await fs.mkdir(absPath, { recursive: true })

  const filesCreated: string[] = []

  if (args.initialize_project) {
    const claudePath = path.join(absPath, 'CLAUDE.md')
    const readmePath = path.join(absPath, 'README.md')

    try {
      await fs.access(claudePath)
    } catch {
      await fs.writeFile(claudePath, CLAUDE_MD, 'utf-8')
      filesCreated.push(toRelative(vaultPath, claudePath))
    }

    try {
      await fs.access(readmePath)
    } catch {
      await fs.writeFile(readmePath, README_MD, 'utf-8')
      filesCreated.push(toRelative(vaultPath, readmePath))
    }
  }

  return {
    path: args.path,
    files_created: filesCreated,
  }
}
