import { useDialogStore } from '../store/useDialogStore'
import { useVaultStore } from '../store/useVaultStore'

const CLAUDE_MD = `# Project

> Auto-generated by Marrow. Edit this file to describe the project for Claude Code.

## Context

- **Purpose**:
- **Stack**:

## Guidelines

-

## File structure

\`\`\`
(describe key directories here)
\`\`\`
`

const README_MD = `# Project

_Add a project description here._
`

/**
 * After creating a folder, call this with the folder path and vault root.
 * If the folder is directly inside the vault root, offers to initialise it
 * as a Claude Code project by writing CLAUDE.md and README.md.
 */
export async function maybeInitProject(folderPath: string): Promise<void> {
  const vaultPath = useVaultStore.getState().vaultPath
  if (!vaultPath || !window.marrow?.vault) return

  // Normalise separators
  const norm = (p: string) => p.replace(/\\/g, '/')
  const parentDir = norm(folderPath).replace(/\/?[^/]+$/, '')
  const vaultNorm = norm(vaultPath).replace(/\/?$/, '')

  // Only prompt for top-level folders (direct children of vault root)
  if (parentDir !== vaultNorm) return

  const confirmed = await useDialogStore.getState().confirm({
    title: 'Initialize as Claude project?',
    message: 'Create CLAUDE.md and README.md in this folder so Claude Code can understand the project?',
    confirmLabel: 'Initialize',
    cancelLabel: 'Skip',
  })

  if (!confirmed) return

  const claudePath = `${folderPath}/CLAUDE.md`.replace(/\//g, '\\')
  const readmePath = `${folderPath}/README.md`.replace(/\//g, '\\')

  const claudeExists = await window.marrow.vault.exists(claudePath)
  const readmeExists = await window.marrow.vault.exists(readmePath)

  if (!claudeExists) await window.marrow.vault.writeFile(claudePath, CLAUDE_MD)
  if (!readmeExists) await window.marrow.vault.writeFile(readmePath, README_MD)

  await useVaultStore.getState().refreshTree()
}
